"""Open-data make aliases: the government manufacturer (tozar) -> the make spellings of the open datasets.

    aliases()        the aliases the engine and the builders use: data/open_data_make_aliases.json (generated by
                     scripts/build_make_aliases.py in the build-open-data Action) merged with the reviewed entries of
                     data/identity_vocabulary.json `open_data_make_aliases` (a reviewed entry always wins its keys)
    strip_country()  "ב מ וו גרמניה" -> "ב מ וו": a tozeret_nm without its country suffix
    propose()        the deterministic proposal: per catalog manufacturer, the source makes (EEA Mk, the make columns
                     of ADEME / EPA / NRCan / CVS) whose consonant skeleton the Hebrew name can produce
                     (data/make_transliteration.json); several equally specific matches are `ambiguous`, none is
                     `unmatched`: both go to the review list, never into the aliases

Nothing is guessed: a proposed alias is always a make spelling a source contains.
"""

from __future__ import annotations

import itertools
import json
import re
from pathlib import Path
from typing import Iterable

DATA = Path(__file__).resolve().parent.parent.parent / "data"
GENERATED_PATH = DATA / "open_data_make_aliases.json"
TRANSLITERATION_PATH = DATA / "make_transliteration.json"
CATALOG_PATH = DATA / "catalog_manufacturers.json"
MAX_VARIANTS = 4096
MIN_FIRST_WORD = 3                                     # consonants a first-word skeleton needs to match alone
_CACHE: dict[str, tuple[float, dict]] = {}


def _json(path: Path) -> dict:
    try:
        mtime = path.stat().st_mtime
    except OSError:
        return {}
    hit = _CACHE.get(str(path))
    if hit and hit[0] == mtime:
        return hit[1]
    try:
        data = json.loads(path.read_text("utf-8"))
    except (OSError, ValueError):
        data = {}
    data = data if isinstance(data, dict) else {}
    _CACHE[str(path)] = (mtime, data)
    return data


def generated(path: Path | str | None = None) -> dict:
    return _json(Path(path or GENERATED_PATH))


def aliases(path: Path | str | None = None) -> dict[str, list[str]]:
    """{tozar: [MAKE, ...]} (upper case): the generated aliases with the reviewed vocabulary entries on top."""
    from ..document_binding import vocabulary

    out: dict[str, list[str]] = {}
    for key, makes in ((generated(path).get("aliases") or {}).items()):
        if isinstance(makes, list) and not str(key).startswith("_"):
            out[str(key)] = sorted({str(m).strip().upper() for m in makes if str(m).strip()})
    for key, makes in ((vocabulary().get("open_data_make_aliases") or {}).items()):
        if isinstance(makes, list) and not str(key).startswith("_"):
            out[str(key)] = sorted({str(m).strip().upper() for m in makes if str(m).strip()})
    return out


def transliteration(path: Path | str | None = None) -> dict:
    return _json(Path(path or TRANSLITERATION_PATH))


def catalog_manufacturers(path: Path | str | None = None) -> list[str]:
    return [str(t) for t in _json(Path(path or CATALOG_PATH)).get("tozar") or []]


def _tokens(name: str, separators: str) -> list[str]:
    return [t for t in re.split("[" + re.escape(separators.replace("'", "")) + "]+", name) if t]


def strip_country(name: str, known: Iterable[str] = (), table: dict | None = None) -> str:
    """A tozeret_nm without its country suffix: the longest known tozar it starts with (on a word boundary), else the
    name with its trailing country words removed."""
    table = table or transliteration()
    text = " ".join(str(name or "").replace("_", " ").replace("-", " ").split())
    for tozar in sorted(set(known), key=len, reverse=True):
        if text == tozar or text.startswith(tozar + " "):
            return tozar
    words = set(table.get("country_words") or [])
    tokens = text.split(" ")
    while len(tokens) > 1 and (tokens[-1] in words or tokens[-1].strip("'\"") in words):
        tokens.pop()
    return " ".join(tokens)


def latin_skeleton(make: str, table: dict | None = None) -> str:
    table = table or transliteration()
    text = re.sub(r"[^a-z]", "", str(make or "").lower())
    for old, new in table.get("latin_rules") or []:
        text = text.replace(old, new)
    drop = set(table.get("latin_drop") or "aeiou")
    text = "".join(ch for ch in text if ch not in drop)
    return re.sub(r"(.)\1+", r"\1", text)


def hebrew_skeletons(name: str, table: dict | None = None) -> set[str]:
    """Every consonant skeleton the Hebrew name can produce (each transliteration, vowels dropped, doubles collapsed)."""
    table = table or transliteration()
    letters, geresh = table.get("letters") or {}, table.get("geresh") or {}
    separators = table.get("separators") or " .-_/'\""
    text = str(name or "")
    if re.search(r"[A-Za-z]", text):                     # a Latin tozar: its own skeleton
        return {latin_skeleton(text, table)}
    options: list[list[str]] = []
    i = 0
    while i < len(text):
        ch = text[i]
        if i + 1 < len(text) and text[i + 1] in "'׳" and ch in geresh:
            options.append(list(geresh[ch]))
            i += 2
            continue
        if ch in separators or ch in "׳\"״":
            i += 1
            continue
        options.append(list(letters.get(ch, [""])))
        i += 1
    drop = set(table.get("latin_drop") or "aeiou")
    out: set[str] = set()
    for combo in itertools.islice(itertools.product(*options), MAX_VARIANTS):
        # the letters already map to normalized consonants: no latin_rules (they would turn "ts" into "z")
        text = "".join(ch for ch in "".join(combo) if ch not in drop)
        out.add(re.sub(r"(.)\1+", r"\1", text))
    out.discard("")
    return out


def _first_word(make: str) -> str:
    parts = [p for p in re.split(r"[\s\-/]+", str(make or "")) if p]
    return parts[0] if parts else ""


def propose(manufacturers: Iterable[str], observed: dict[str, Iterable[str]], existing: dict[str, list[str]] | None = None,
            table: dict | None = None) -> dict:
    """{aliases, ambiguous, unmatched, reviewed}: per manufacturer the source makes it spells (module docstring).

    `observed` is {dataset: makes}. A make matches a manufacturer when its whole-name skeleton, or its first-word
    skeleton of at least MIN_FIRST_WORD consonants, is one of the manufacturer's Hebrew skeletons; the matches with the
    longest skeleton are kept; if those come from more than one distinct skeleton, or name makes with different first
    words, it is ambiguous. `existing` (the reviewed vocabulary) is kept as is and never re-proposed."""
    table = table or transliteration()
    existing = {k: list(v) for k, v in (existing or {}).items() if isinstance(v, list) and not k.startswith("_")}
    makes: dict[str, set[str]] = {}
    for dataset, values in observed.items():
        for make in values or []:
            name = " ".join(str(make or "").split()).upper()
            if name:
                makes.setdefault(name, set()).add(dataset)
    index: dict[str, set[str]] = {}
    for make in makes:
        skeletons = {latin_skeleton(make, table)}
        first = latin_skeleton(_first_word(make), table)
        if len(first) >= MIN_FIRST_WORD:                 # "DE" of DE TOMASO ("d") would match AUDI's Hebrew name
            skeletons.add(first)
        for skeleton in skeletons - {""}:
            index.setdefault(skeleton, set()).add(make)
    aliases, ambiguous, unmatched = {}, {}, []
    for tozar in sorted(set(manufacturers)):
        if tozar in existing:
            continue
        hits = {s: index[s] for s in hebrew_skeletons(tozar, table) if s in index}
        if not hits:
            unmatched.append(tozar)
            continue
        longest = max(len(s) for s in hits)
        best = {s: m for s, m in hits.items() if len(s) == longest}
        if len(best) > 1:
            ambiguous[tozar] = {s: sorted(m) for s, m in sorted(best.items())}
            continue
        (skeleton, found), = best.items()
        # every make spelled with that skeleton: e.g. MERCEDES-BENZ / MERCEDES BENZ share the first-word skeleton;
        # makes with different first words under one skeleton are not variants of one make: review
        if len({_first_word(m) for m in found}) > 1:
            ambiguous[tozar] = {skeleton: sorted(found)}
            continue
        aliases[tozar] = sorted(found)
    claimed: dict[str, list[str]] = {}
    for tozar, found in aliases.items():
        for make in found:
            claimed.setdefault(make, []).append(tozar)
    for make, owners in claimed.items():                  # one make proposed for two manufacturers: review both
        if len(owners) > 1:
            for tozar in owners:
                if tozar in aliases:
                    ambiguous[tozar] = {"shared_make": [make], "with": sorted(set(owners) - {tozar})}
                    aliases.pop(tozar)
    return {"aliases": aliases, "ambiguous": ambiguous, "unmatched": unmatched, "reviewed": existing,
            "sources": {make: sorted(ds) for make, ds in sorted(makes.items())}}
