"""Open-data make aliases: the government manufacturer (tozar) -> the make spellings of the open datasets (E4).

    canonical()        data/make_canonical.json: the reviewed table tozar -> canonical Latin make(s); `model_gated`
                       makes (one tozar naming several makes) count only with a catalog model match
    normalize_make()   the normalization key of a make spelling: upper case, punctuation stripped (B.M.W. -> BMW),
                       legal-form words and address tails dropped, spaces collapsed (LANDROVER = LAND ROVER)
    spellings_of()     per canonical make, the spellings of a dataset whose key equals the make's key: nothing else,
                       never fuzzy ("HIUNDAI", "JEPP", "1OYOTA" are no spelling of anything)
    aliases()          what the engine and the builders use: each tozar's canonical make names, the spellings of
                       data/open_data_make_aliases.json (generated by scripts/build_make_aliases.py from make_canonical.json
                       and the probe's distinct makes) and of the last build's manifest, plus the reviewed extra
                       spellings of identity_vocabulary `open_data_make_aliases`
    row_filter()       whether a dataset row counts: its spelling normalizes to a plain make, or to a model-gated make
                       and its model matches a catalog model family of that tozar (never by make alone)
    tozar_gate()       the match-time gate of one target tozar: a make with an `own_tozar_only` tozar of its own (MINI,
                       CUPRA) counts by make alone for that tozar's rows only; under ב מ וו / סיאט it stays model-gated
"""

from __future__ import annotations

import json
import re
import unicodedata
from pathlib import Path
from typing import Any, Callable, Iterable

DATA = Path(__file__).resolve().parent.parent.parent / "data"
GENERATED_PATH = DATA / "open_data_make_aliases.json"
CANONICAL_PATH = DATA / "make_canonical.json"
CATALOG_PATH = DATA / "catalog_manufacturers.json"
_CACHE: dict[str, tuple[float, dict]] = {}
_DIGIT = re.compile(r"\d")
_JOIN = re.compile(r"[.'’`´]")
_SEPARATE = re.compile(r"[^A-Z0-9 ]+")


def _json(path: Path) -> dict:
    try:
        mtime = path.stat().st_mtime
    except OSError:
        return {}
    hit = _CACHE.get(str(path))
    if hit and hit[0] == mtime:
        return hit[1]
    try:
        data = json.loads(path.read_text("utf-8"))
    except (OSError, ValueError):
        data = {}
    data = data if isinstance(data, dict) else {}
    _CACHE[str(path)] = (mtime, data)
    return data


def generated(path: Path | str | None = None) -> dict:
    return _json(Path(path or GENERATED_PATH))


def canonical(path: Path | str | None = None) -> dict:
    return _json(Path(path or CANONICAL_PATH))


def catalog_manufacturers(path: Path | str | None = None) -> list[str]:
    return [str(t) for t in _json(Path(path or CATALOG_PATH)).get("tozar") or []]


def spelling(value: Any) -> str:
    """A dataset's make spelling as the snapshots store it: upper case, whitespace collapsed."""
    return " ".join(str(value or "").split()).upper()


def _words(table: dict, key: str) -> set[str]:
    return {str(w).upper() for w in ((table.get("normalization") or {}).get(key) or [])}


def normalize_make(value: Any, table: dict | None = None) -> str:
    """The normalization key of a make spelling ("" when nothing is left). See data/make_canonical.json
    `normalization`: "AUDI AG DE-85045 INGOLSTADT" -> AUDI, "B.M.W." -> BMW, "LAND ROVER" -> LANDROVER."""
    table = canonical() if table is None else table
    legal, descriptors = _words(table, "legal_forms"), _words(table, "descriptors")
    text = unicodedata.normalize("NFKD", str(value or "").upper())
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    kept: list[str] = []
    for token in text.split():
        if _DIGIT.search(token):                      # an address tail (postcode, street number) or a typo ("1OYOTA")
            break
        words = _SEPARATE.sub(" ", _JOIN.sub("", token)).split()
        stop = False
        for word in words:
            if word in legal:
                stop = True
                break
            if word not in descriptors:
                kept.append(word)
        if stop:
            break
    return "".join(kept)


def tozar_makes(tozar: str, table: dict | None = None) -> tuple[list[str], list[str]]:
    """(plain makes, model-gated makes) of a tozar; ([], []) for an unmapped one."""
    entry = ((canonical() if table is None else table).get("tozar") or {}).get(tozar) or {}
    return [str(m) for m in entry.get("makes") or []], [str(m) for m in entry.get("model_gated") or []]


def canonical_makes(table: dict | None = None) -> list[str]:
    """Every canonical make of the table (plain and model-gated), sorted."""
    table = canonical() if table is None else table
    out: set[str] = set()
    for tozar in table.get("tozar") or {}:
        plain, gated = tozar_makes(tozar, table)
        out |= set(plain) | set(gated)
    return sorted(out)


_MEMO_TABLES = 8                      # canonical_of: the tables memoized at once (the reviewed one, plus test tables)
_MEMO_VALUES = 50_000                 # spellings memoized per table (a dataset has a few hundred)
_CANONICAL_MEMO: dict[int, tuple[dict, dict[str, str], dict[Any, str | None]]] = {}


def _memo(table: dict) -> tuple[dict[str, str], dict[Any, str | None]]:
    """({normalization key: canonical make}, {spelling: canonical_of}) of one table object (a table re-read after an
    edit is a new object: a new memo). The first canonical make in sorted order wins a shared key, as before."""
    hit = _CANONICAL_MEMO.get(id(table))
    if hit is not None and hit[0] is table:
        return hit[1], hit[2]
    if len(_CANONICAL_MEMO) >= _MEMO_TABLES:
        _CANONICAL_MEMO.clear()
    keys: dict[str, str] = {}
    for make in canonical_makes(table):
        keys.setdefault(normalize_make(make, table), make)
    _CANONICAL_MEMO[id(table)] = (table, keys, {})
    return keys, _CANONICAL_MEMO[id(table)][2]


def canonical_of(value: Any, table: dict | None = None) -> str | None:
    """The canonical make a spelling normalizes to (None: no make; never fuzzy). Memoized per spelling and table: the
    match calls it once per candidate row (E4 profile: 94 % of a cold facts key before the memo)."""
    table = canonical() if table is None else table
    keys, values = _memo(table)
    memo_key = value if isinstance(value, (str, int, float, type(None))) else str(value)
    if memo_key in values:
        return values[memo_key]
    key = normalize_make(value, table)
    out = keys.get(key) if key else None
    if len(values) >= _MEMO_VALUES:
        values.clear()
    values[memo_key] = out
    return out


def spellings_of(values: Iterable[Any], table: dict | None = None) -> dict[str, list[str]]:
    """{canonical make: [the spellings among `values` that normalize to it]} (spellings as stored: `spelling`)."""
    table = canonical() if table is None else table
    keys = {normalize_make(m, table): m for m in canonical_makes(table)}
    keys.pop("", None)
    out: dict[str, set[str]] = {}
    for value in values:
        make = keys.get(normalize_make(value, table))
        if make and spelling(value):
            out.setdefault(make, set()).add(spelling(value))
    return {make: sorted(found) for make, found in sorted(out.items())}


def catalog_families(tozar: str) -> list[str]:
    """The catalog model families of a tozar: data/catalog_trim_index.json `family` plus the reviewed model spellings of
    identity_vocabulary `open_data_model_aliases` (`tozar|family`)."""
    from ..document_binding import vocabulary

    families: set[str] = set()
    for key in (_json(DATA / "catalog_trim_index.json").get("entries") or {}):
        parts = str(key).split("|")
        if len(parts) > 1 and parts[0] == tozar and parts[1]:
            families.add(parts[1])
    for key, values in (vocabulary().get("open_data_model_aliases") or {}).items():
        if str(key).startswith(f"{tozar}|") and isinstance(values, list):
            families.add(str(key).split("|", 1)[1])
            families.update(str(v) for v in values)
    return sorted(families)


def gate_families(families: Iterable[str], makes: Iterable[str], table: dict | None = None) -> list[str]:
    """The catalog model families a model-gated make is checked against: at least two characters with a Latin letter or
    digit, never Hebrew, and never a family that is itself a make name of the tozar ("mini", "cupra": make alone)."""
    table = canonical() if table is None else table
    names = {normalize_make(m, table) for m in makes} | {re.sub(r"[^A-Z0-9]", "", str(m).upper()) for m in makes}
    out = set()
    for family in families:
        text = " ".join(str(family or "").split()).upper()
        if len(text) < 2 or not re.search(r"[A-Z0-9]", text) or re.search(r"[\u0590-\u05FF]", text):
            continue
        if re.sub(r"[^A-Z0-9]", "", text) in names:
            continue
        out.add(text)
    return sorted(out)


def model_gates(table: dict | None = None) -> dict[str, dict[str, list[str]]]:
    """{model-gated canonical make: {tozar: [the families its rows must match]}}."""
    table = canonical() if table is None else table
    out: dict[str, dict[str, list[str]]] = {}
    for tozar in table.get("tozar") or {}:
        plain, gated = tozar_makes(tozar, table)
        if gated:
            families = gate_families(catalog_families(tozar), plain + gated, table)
            for make in gated:
                out.setdefault(make, {})[tozar] = families
    return out


_TOZAR_GATES: dict[tuple[int, str], tuple[dict, Callable[[dict], bool] | None]] = {}


def own_tozar_only_makes(table: dict | None = None) -> set[str]:
    """The model-gated makes every plain mapping of which is an `own_tozar_only` tozar (מיני -> MINI, קופרה -> CUPRA):
    by make alone for the rows of that tozar only. CHRYSLER / DODGE / JEEP stay out (plain under קרייזלר / דודג' /
    ג'יפ, not flagged): the gate of דיימלר קרייזלר never applied at match time and still does not."""
    table = canonical() if table is None else table
    entries = table.get("tozar") or {}
    gated = {m for t in entries for m in tozar_makes(t, table)[1]}
    out = set()
    for make in gated:
        owners = [t for t in entries if make in tozar_makes(t, table)[0]]
        if owners and all((entries.get(t) or {}).get("own_tozar_only") for t in owners):
            out.add(make)
    return out


def tozar_gate(tozar: Any, table: dict | None = None) -> Callable[[dict], bool] | None:
    """keep(row) at match time for a target of one tozar, None when nothing is gated there: a row of a model-gated make
    of this tozar that is `own_tozar_only` elsewhere (MINI under ב מ וו, CUPRA under סיאט) counts only when its model
    text matches a catalog model family of this tozar (gate_families), exactly as the build's row_filter kept it before
    that make had a tozar of its own; every other row passes."""
    table = canonical() if table is None else table
    key = (id(table), str(tozar or ""))
    hit = _TOZAR_GATES.get(key)
    if hit is not None and hit[0] is table:
        return hit[1]
    if len(_TOZAR_GATES) > 256:
        _TOZAR_GATES.clear()
    plain, gated = tozar_makes(str(tozar or ""), table)
    strict = [m for m in gated if m in own_tozar_only_makes(table)]
    gate = None
    if strict:
        families = gate_families(catalog_families(str(tozar)), plain + gated, table)
        makes = set(strict)

        def gate(row: dict) -> bool:
            if canonical_of(row.get("make"), table) not in makes:
                return True
            text = " ".join(str(row.get(k) or "") for k in ("model", "variant", "version"))
            return model_matches(text, families)
    _TOZAR_GATES[key] = (table, gate)
    return gate


def _manifest_spellings() -> dict[str, list[str]]:
    """{canonical make: spellings} the last build recorded in data/open/manifest.json (`make_spellings`)."""
    from . import datasets as ds

    out: dict[str, set[str]] = {}
    for entry in ((ds.manifest().get("datasets") or {}).values()):
        for make, values in ((entry or {}).get("make_spellings") or {}).items() if isinstance(entry, dict) else ():
            out.setdefault(str(make), set()).update(spelling(v) for v in values or [] if spelling(v))
    return {k: sorted(v) for k, v in out.items()}


def aliases(path: Path | str | None = None) -> dict[str, list[str]]:
    """{tozar: [MAKE, ...]} (upper case): every tozar's canonical make names, the spellings the generated file
    (data/open_data_make_aliases.json) and the last build's manifest found for them, and the reviewed extra spellings of
    identity_vocabulary `open_data_make_aliases`."""
    from ..document_binding import vocabulary

    table = canonical()
    built = _manifest_spellings()
    out: dict[str, set[str]] = {}
    for tozar in table.get("tozar") or {}:
        plain, gated = tozar_makes(tozar, table)
        for make in plain + gated:
            out.setdefault(tozar, set()).update({spelling(make), *built.get(make, [])})
    for source in ((generated(path).get("aliases") or {}), (vocabulary().get("open_data_make_aliases") or {})):
        for key, makes in source.items():
            if isinstance(makes, list) and not str(key).startswith("_"):
                out.setdefault(str(key), set()).update(spelling(m) for m in makes if spelling(m))
    return {k: sorted(v) for k, v in out.items() if v}


def model_matches(text: str, models: Iterable[str]) -> bool:
    """A catalog model family as a whole word of the row's model text (case-insensitive)."""
    upper = str(text or "").upper()
    return any(re.search(rf"(?<![A-Z0-9]){re.escape(str(m).upper())}(?![A-Z0-9])", upper) for m in models if m)


def row_filter(table: dict | None = None) -> Callable[[Any, str], bool]:
    """keep(make, model_text): whether a dataset row counts. Its spelling normalizes to a plain make of some tozar (or
    is a reviewed vocabulary spelling), or to a model-gated make and its model matches a catalog model family of a tozar
    gating it. Never a model-gated make by make alone; a spelling that normalizes to no make never counts."""
    from ..document_binding import vocabulary

    table = canonical() if table is None else table
    plain = {m for t in table.get("tozar") or {} for m in tozar_makes(t, table)[0]}
    gates = model_gates(table)
    reviewed = {spelling(m) for k, ms in (vocabulary().get("open_data_make_aliases") or {}).items()
                if isinstance(ms, list) and not str(k).startswith("_") for m in ms}
    kinds: dict[str, tuple[str, list[list[str]]]] = {}

    def kind(value: str) -> tuple[str, list[list[str]]]:
        if value not in kinds:
            make = canonical_of(value, table)
            if value in reviewed or make in plain:
                kinds[value] = ("plain", [])
            elif make in gates:
                kinds[value] = ("gated", list(gates[make].values()))
            else:
                kinds[value] = ("none", [])
        return kinds[value]

    def keep(make: Any, model_text: str) -> bool:
        what, families = kind(spelling(make))
        if what == "plain":
            return True
        return what == "gated" and any(model_matches(model_text, models) for models in families)
    return keep
