"""Write DATA_SOURCES.md: every dataset TRIPY ingests, with its publisher (ministry / agency), portal, dataset name,
resource id, licence and retrieval date, from the committed manifests (data/gov/manifest.json, data/open/manifest.json,
data/gov_registry_index.json) and the configs (data/gov_datasets.json, data/open_datasets.json,
data/source_policy.json). A dataset not built yet says so. Run by the build-gov-datasets Action (and by hand).

    python scripts/data_sources.py [--out DATA_SOURCES.md]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

OPEN_PUBLISHERS = {
    "eea_co2_cars": ("European Environment Agency (EEA)", "DISCODATA / EEA datahub"),
    "ademe_car_labelling": ("ADEME (Agence de la transition écologique), France", "data.ademe.fr"),
    "epa_fueleconomy": ("US Environmental Protection Agency / US Department of Energy", "fueleconomy.gov"),
    "nrcan_fuel_ratings": ("Natural Resources Canada", "open.canada.ca"),
    "tc_cvs": ("Transport Canada", "open.canada.ca"),
    "nhtsa_vpic": ("US National Highway Traffic Safety Administration", "vpic.nhtsa.dot.gov"),
}


def _json(path: Path) -> dict:
    try:
        data = json.loads(path.read_text("utf-8"))
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def _cell(value) -> str:
    return "—" if value in (None, "", []) else str(value).replace("|", "/").replace("\n", " ")


def rows(root: Path = ROOT) -> list[list[str]]:
    out = []
    gov_cfg = _json(root / "data" / "gov_datasets.json")
    gov_manifest = _json(root / "data" / "gov" / "manifest.json").get("datasets") or {}
    for name, spec in (gov_cfg.get("datasets") or {}).items():
        entry = gov_manifest.get(name) or {}
        built = {r.get("resource_id"): r for r in entry.get("resources") or [] if isinstance(r, dict)}
        for resource in spec.get("resources") or []:
            rid = resource["resource_id"]
            res = built.get(rid) or {}
            title = res.get("package_title") or f"{spec.get('title_he')} ({spec.get('title')})"
            out.append([_cell(res.get("organization") or spec.get("ministry")), "data.gov.il",
                        f"{title} — {name}, {resource.get('role')}", f"`{rid}`",
                        _cell(res.get("license") or f"{spec.get('stated_licence')} (as briefed; not built yet)"),
                        _cell(str(res.get("downloaded_at") or "")[:10] or "not built yet")])
    index = _json(root / "data" / "gov_registry_index.json")
    if index.get("resource_id"):
        out.append(["Ministry of Transport and Road Safety", "data.gov.il",
                    "מספרי רישוי של כלי רכב פרטיים ומסחריים (tyre-size index, data/gov_registry_index.json)",
                    f"`{index['resource_id']}`", "Israeli government open data (data.gov.il terms)",
                    _cell(str(index.get("generated_at") or "")[:10])])
    policy = {e.get("id"): e for e in (_json(root / "data" / "source_policy.json").get("entries") or [])}
    open_cfg = _json(root / "data" / "open_datasets.json").get("datasets") or {}
    open_manifest = _json(root / "data" / "open" / "manifest.json").get("datasets") or {}
    for name, spec in open_cfg.items():
        publisher, portal = OPEN_PUBLISHERS.get(name, ("—", "—"))
        entry = open_manifest.get(name) or {}
        licence = (policy.get(spec.get("policy_id") or name) or {}).get("licence")
        retrieved = str(entry.get("built_at") or "")[:10] or ("at need (identity keys only, never bulk-stored)"
                                                              if spec.get("identity_only") else "not built yet")
        out.append([publisher, portal, f"{spec.get('label')} ({name})", _cell(spec.get("source_url")),
                    _cell(licence), retrieved])
    return out


def render(root: Path = ROOT) -> str:
    lines = ["# Data sources", "",
             "Every vehicle data source TRIPY ingests (and serves to yeda-rechev through the facts API). Generated by "
             "`scripts/data_sources.py` from the committed manifests; do not edit by hand.", "",
             "data.gov.il terms permit copying, storage, processing, derived works, commercial use and public display, "
             "with the source metadata kept and no misleading presentation or privacy harm. TRIPY stores government "
             "datasets at model / model-year level only: no per-vehicle record is stored or served.", "",
             "| publisher | portal | dataset | resource id / source | licence (as stated) | retrieved |",
             "|---|---|---|---|---|---|"]
    lines += ["| " + " | ".join(r) + " |" for r in rows(root)]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default=str(ROOT / "DATA_SOURCES.md"))
    args = parser.parse_args(argv)
    Path(args.out).write_text(render(), "utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
